#!/usr/bin/env ruby

require './lib/bt/version'
require 'yaml'

y 'gem' => {'run' => 'bundle install --no-color --local && bundle exec rake build',
            'results' => ["pkg/build-thing-#{BT::VERSION}.gem"],
            'needs' => ['spec']}
