#!/usr/bin/env ruby

require 'bt/version'
require 'yaml'

y 'gem' => {'run' => 'bundle install --local && bundle exec rake build',
            'results' => ["pkg/build-thing-#{BT::VERSION}.gem"],
            'needs' => ['spec']}
